#!/usr/bin/python3
from sys import argv


def find_factors(number):
    if number % 2 == 0:
        print("{}={}*{}".format(number, number // 2, 2))
        return
    for i in range(3, number):
        if number % i == 0:
            print("{}={}*{}".format(number, number // i, i))
            return
    print("{}={}*{}".format(number, number, 1))


def factorize_numbers():
    if len(argv) != 2:
        exit()
    try:
        file_name = argv[1]
        with open(file_name) as file:
            for line in file:
                number = int(line.strip())
                find_factors(number)
    except IndexError:
        pass


if __name__ == "__main__":
    factorize_numbers()
